String Manipulation 3 | Nick Kniola
nickkniola/c1020-code-solutions pull request #54
Opened 2020-10-23 02:13 UTC by nickkniola

![Screen Shot 2020-10-22 at 7 13 31 PM](https://user-images.githubusercontent.com/65201044/96948515-b2aaf700-149a-11eb-8303-1cfb9d19427c.png)

2020-11-11 20:02 UTC, uzair-ashraf requested changes

2020-11-11 20:02 UTC, uzair-ashraf commented on string-manipulation-3/src/title-case.js
> +        continue;
You don't need all these continute statements, you can switch if and else if statements to get the same outcome.

2020-11-16 23:55 UTC, thebearingedge requested changes

2020-11-16 23:55 UTC, thebearingedge commented on string-manipulation-3/src/is-palindromic.js
> +  }
You could simplify this a bit by tracking two indexes at once. For example `i` to start at the beginning and `j` to start at the end. Your loop's condition could be that `i < j` and as long as the characters at `i` and `j` are equal, it's a palindrome.

2020-11-16 23:55 UTC, thebearingedge commented on string-manipulation-3/src/is-palindromic.js
> +  }
Then you wouldn't need to make new substrings every iteration.

2020-11-19 22:52 UTC, thebearingedge approved these changes

2020-11-19 23:12 UTC, merged